security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  providers:
    in_memory:
      memory:
        users:
          user1:
            password: 'parola_test1'
            roles: 'ROLE_USER'
          user2:
            password: 'parola_test2'
            roles: 'ROLE_USER'

  firewalls:
    main:
        provider: in_memory
        anonymous: true
        form_login:
          login_path: login
          check_path: login
        logout:
          path: logout
          target: homepage
  #access_control:
    #- { path: '^/listing', roles: ROLE_USER }